Create client
iTechArt-RubyLab/online-booking-system pull request #13
Opened 2022-01-24 18:04 UTC by Vgoylo

Create models client & refactoring salons

2022-01-24 20:42 UTC, TehanovAnton commented on app/models/client.rb
> +  #validates :rating, :work_email, :work_phone_number, :status, :salon_id, allow_blank: true
validations like here #12

2022-01-25 01:32 UTC, dmokreckiy commented on app/models/visit_service.rb
> +  belongs_to :servise
servi`c`e

2022-01-25 01:34 UTC, dmokreckiy requested changes
Fix association naming

2022-01-27 08:29 UTC, Rub1st approved these changes

2022-01-27 11:00 UTC, merged