Aded sorting in controller to salons
iTechArt-RubyLab/online-booking-system pull request #9
Opened 2022-01-23 20:19 UTC by Vgoylo

Add sorting in controller to salons

2022-01-24 16:37 UTC, TehanovAnton commented on app/controllers/api/v1/salons_controller.rb
> +        if params[:sort]
look my comments in #11

2022-01-25 01:10 UTC, dmokreckiy requested changes
Please refactor logic and strong params

2022-01-25 01:10 UTC, dmokreckiy commented on app/controllers/api/v1/salons_controller.rb
> +        render json: params[:sort] ? Salon.order(sort_params.to_h) : Salon.all
please separate logic from ternary operator and extract it to normal variables to improve readability.

2022-01-25 01:10 UTC, dmokreckiy commented on app/controllers/api/v1/salons_controller.rb
> +        params.require(:sort).permit!
`.permit!`? Why use strong params at all then?
Please use strong params normally.

2022-01-27 14:55 UTC, GEK62 approved these changes

2022-01-28 14:13 UTC, merged